from __future__ import annotations


def _normalize(text: str) -> str:
    translation = str.maketrans(
        {
            "ą": "a",
            "ć": "c",
            "ę": "e",
            "ł": "l",
            "ń": "n",
            "ó": "o",
            "ś": "s",
            "ż": "z",
            "ź": "z",
        }
    )
    return text.lower().translate(translation)


def categorize_query(query: str) -> str:
    lowered = _normalize(query)
    keyword_map = {
        "ksef": (
            "ksef",
            "krajowy system e-faktur",
            "e-faktur",
            "e-faktura",
            "faktura ustrukturyzowana",
            "faktury ustrukturyzowane",
            "numer ksef",
            "token ksef",
            "uprawnienia ksef",
        ),
        "faktury_korygujące": (
            "faktura korygujaca",
            "faktury korygujace",
            "korekta faktury",
            "korygujacej",
            "korygujaca",
            "nota korygujaca",
            "blad na fakturze",
            "bledny nip",
            "korekta",
        ),
        "korekty": (
            "korekta vat",
            "korekty vat",
            "korekta podatku",
            "korekta odliczenia",
            "ulga na zle dlugi",
            "zle dlugi",
        ),
        "pit": (
            "pit",
            "podatek dochodowy",
            "zaliczka na podatek",
            "zeznanie roczne",
            "pit-36",
            "pit-37",
            "pit-11",
            "ulga na dzieci",
            "kwota wolna",
            "skala podatkowa",
            "podatek liniowy",
        ),
        "cit": (
            "cit",
            "podatek dochodowy od osob prawnych",
            "estonski cit",
            "ryczalt od dochodow spolek",
        ),
        "zus": (
            "zus",
            "skladki",
            "skladka zdrowotna",
            "skladka spoleczna",
            "maly zus",
            "preferencyjne skladki",
            "dra",
            "rca",
        ),
        "kadry": (
            "kodeks pracy",
            "umowa o prace",
            "urlop",
            "wynagrodzenie minimalne",
            "nadgodziny",
            "wypowiedzenie",
            "swiadectwo pracy",
            "l4",
            "zasilek chorobowy",
        ),
        "ordynacja": (
            "ordynacja podatkowa",
            "przedawnienie",
            "kontrola podatkowa",
            "interpretacja indywidualna",
            "nadplata",
            "zaleglosc podatkowa",
            "odsetki za zwloke",
            "pelnomocnictwo",
        ),
        "rachunkowosc": (
            "bilans",
            "rachunek zyskow i strat",
            "sprawozdanie finansowe",
            "ksiegi rachunkowe",
            "kpir",
            "srodki trwale",
            "amortyzacja",
            "inwentaryzacja",
        ),
        "terminy": (
            "termin",
            "terminy",
            "do kiedy",
            "kiedy zlozyc",
            "termin zlozenia",
            "deklaracja",
            "deklaracje",
            "jpk",
            "jpk_v7",
            "jpk_vat",
            "ewidencja",
            "okres rozliczeniowy",
            "miesiecznie",
            "kwartalnie",
        ),
        "jpk": (
            "jpk",
            "jpk_v7",
            "jpk_vat",
            "gtu",
            "oznaczenia jpk",
        ),
        "podatek_naliczony": (
            "podatek naliczony",
            "vat naliczony",
            "odliczenie vat",
            "odliczyc vat",
            "odliczenia",
            "zakup",
            "nabycie",
        ),
        "podatek_nalezny": (
            "podatek nalezny",
            "vat nalezny",
            "obowiazek podatkowy",
            "sprzedaz",
            "dostawa towarow",
            "import uslug",
            "stawka vat",
        ),
        "fakturowanie": (
            "faktura",
            "faktury",
            "wystawic fakture",
            "wystawienie faktury",
            "duplikat faktury",
            "paragon",
            "numer faktury",
        ),
        "vat": (
            "vat",
            "zwolnienie z vat",
            "rejestracja vat",
            "vat ue",
            "zwrot vat",
            "podatek od towarow i uslug",
        ),
    }
    for category, keywords in keyword_map.items():
        if any(keyword in lowered for keyword in keywords):
            return category
    return "ogólne"
