from __future__ import annotations

import re
import unicodedata


def _normalize(text: str) -> str:
    normalized = unicodedata.normalize("NFKD", text.lower())
    without_accents = "".join(
        character for character in normalized if not unicodedata.combining(character)
    )
    return re.sub(r"\s+", " ", without_accents).strip()


def categorize_query(query: str) -> str:
    lowered = _normalize(query)
    keyword_map = (
        (
            "ksef",
            (
                "ksef",
                "krajowy system e-faktur",
                "e-faktur",
                "e-faktura",
                "faktura ustrukturyzowana",
                "faktury ustrukturyzowane",
                "numer ksef",
                "token ksef",
                "uprawnienia ksef",
            ),
        ),
        (
            "rachunkowosc",
            (
                "bilans",
                "sprawozdanie",
                "sprawozdanie finansowe",
                "rzis",
                "rachunek zyskow",
                "rachunek zyskow i strat",
                "inwentaryzacj",
                "spis z natury",
                "potwierdzenie sald",
                "amortyzacja bilansowa",
                "dowod ksiegowy",
                "kpir",
                "pełne ksiegi",
                "pelne ksiegi",
                "e-sprawozdanie",
                "e sprawozdanie",
                "krs",
                "ustawa o rachunkowosci",
                "wycena aktywow",
                "rezerwa",
                "rezerwy",
                "rmk",
                "odpis aktualizujacy",
                "podatek odroczony",
            ),
        ),
        (
            "jpk",
            (
                "jpk",
                "jpk_v7",
                "jpk_v7m",
                "jpk_v7k",
                "gtu",
                "znacznik",
                "plik kontrolny",
                "ewidencja vat",
                "korekta jpk",
            ),
        ),
        (
            "cit",
            (
                "cit",
                "podatek dochodowy od osob prawnych",
                "spółka z o.o.",
                "spolka z o.o.",
                "spółka akcyjna",
                "spolka akcyjna",
                "stawka cit",
                "estonski cit",
                "ryczałt od dochodow spolek",
                "ryczalt od dochodow spolek",
                "wht",
                "podatek u zrodla",
                "ceny transferowe",
                "tp",
                "tpr",
                "cit-8",
                "ryczałt od dochodow",
                "ryczalt od dochodow",
                "małý podatnik cit",
                "maly podatnik cit",
                "mały podatnik cit",
                "ift-2r",
                "strata podatkowa",
            ),
        ),
        (
            "zus",
            (
                "zus",
                "składka",
                "skladka",
                "składki",
                "skladki",
                "składka zdrowotna",
                "skladka zdrowotna",
                "składka społeczna",
                "skladka spoleczna",
                "ubezpieczenie społeczne",
                "ubezpieczenie spoleczne",
                "ubezpieczenie zdrowotne",
                "ubezpieczenie chorobowe",
                "fp",
                "fgsp",
                "dra",
                "rca",
                "zasiłek",
                "zasilek",
                "zasiłek chorobowy",
                "zasilek chorobowy",
                "zasiłek macierzynski",
                "zasilek macierzynski",
                "chorobowe",
                "macierzynski",
                "preferencyjny zus",
                "małý zus",
                "maly zus",
                "mały zus",
                "mały zus plus",
                "maly zus plus",
                "ulga na start",
                "zbieg tytulow",
                "podstawa wymiaru",
                "okres wyczekiwania",
            ),
        ),
        (
            "pit",
            (
                "pit",
                "podatek dochodowy",
                "zaliczka na podatek",
                "zeznanie roczne",
                "pit-36",
                "pit-36l",
                "pit-37",
                "pit-11",
                "ulga na dzieci",
                "kwota wolna",
                "skala podatkowa",
                "podatek liniowy",
                "formy opodatkowania",
                "ryczałt",
                "ryczalt",
                "karta podatkowa",
                "jdg",
                "działalnosc gospodarcza",
                "dzialalnosc gospodarcza",
            ),
        ),
        (
            "kadry",
            (
                "kodeks pracy",
                "umowa o prace",
                "umow na czas",
                "umowa na czas",
                "wypowiedzeni",
                "okres wypowiedzenia",
                "rozwiazanie umowy",
                "zwolnienie z pracy",
                "zwolnienie pracownika",
                "zwolnienie dyscyplinarne",
                "urlop",
                "urlop wypoczynkowy",
                "urlop macierzynski",
                "nadgodziny",
                "czas pracy",
                "swiadectwo pracy",
                "swiadectwo",
                "okres probny",
                "praca zdalna",
                "bhp",
                "badania lekarskie",
                "macierzynski",
                "rodzicielski",
                "ekwiwalent",
                "wynagrodzenie minimalne",
                "l4",
            ),
        ),
        (
            "ordynacja",
            (
                "ordynacja podatkowa",
                "przedawnienie",
                "kontrola podatkowa",
                "interpretacja indywidualna",
                "nadpłata",
                "nadplata",
                "zaległosc podatkowa",
                "zaleglosc podatkowa",
                "odsetki za zwłoke",
                "odsetki za zwloke",
                "pełnomocnictwo",
                "pelnomocnictwo",
            ),
        ),
        (
            "faktury_koryguj\u0105ce",
            (
                "faktura korygujaca",
                "faktury korygujace",
                "korekta faktury",
                "korekta",
                "korekty",
                "korygujacej",
                "korygujaca",
                "nota korygujaca",
                "bład na fakturze",
                "blad na fakturze",
                "błedny nip",
                "bledny nip",
                "nip",
            ),
        ),
        (
            "korekty",
            (
                "korekta vat",
                "korekty vat",
                "korekta podatku",
                "korekta odliczenia",
                "ulga na złe długi",
                "ulga na zle dlugi",
                "złe długi",
                "zle dlugi",
            ),
        ),
        (
            "fakturowanie",
            (
                "faktura",
                "faktury",
                "wystawic fakture",
                "wystawienie faktury",
                "duplikat faktury",
                "paragon",
                "numer faktury",
            ),
        ),
        (
            "podatek_naliczony",
            (
                "podatek naliczony",
                "vat naliczony",
                "odliczenie vat",
                "odliczyc vat",
                "odliczenia",
                "zakup",
                "nabycie",
            ),
        ),
        (
            "podatek_nale\u017cny",
            (
                "podatek nalezny",
                "vat nalezny",
                "obowiazek podatkowy",
                "sprzedaz",
                "dostawa towarow",
                "import uslug",
                "stawka vat",
            ),
        ),
        (
            "vat",
            (
                "vat",
                "zwolnienie z vat",
                "rejestracja vat",
                "vat ue",
                "zwrot vat",
                "podatek od towarow i uslug",
                "mechanizm podzielonej płatnosci",
                "mechanizm podzielonej platnosci",
                "mpp",
                "split payment",
            ),
        ),
        (
            "terminy",
            (
                "termin",
                "terminy",
                "do kiedy",
                "kiedy złozyc",
                "kiedy zlozyc",
                "termin złozenia",
                "termin zlozenia",
                "deklaracja",
                "deklaracje",
                "okres rozliczeniowy",
                "miesiecznie",
                "kwartalnie",
            ),
        ),
    )
    for category, keywords in keyword_map:
        if any(keyword in lowered for keyword in keywords):
            return category
    return "og\u00f3lne"
